In [151]:
import pandas as pd

In [152]:
d=pd.read_csv(r"C:\Users\sivas\Downloads\customer_churn_dataset.csv")
d

     age  monthly_charges  tenure_months  support_calls  churned
0     22           113.81             57              1        0
1     59            66.97             16              5        1
2     41            20.56             34              1        0
3     56           119.92             37              4        1
4     69            24.78             60              3        0
..   ...              ...            ...            ...      ...
295   23           115.90             56              0        1
296   44            35.21             67              2        1
297   24            25.06             23              5        1
298   29            26.75             26              1        1
299   58            63.55             43              2        1

[300 rows x 5 columns]

In [153]:
d.columns

Index(['age', 'monthly_charges', 'tenure_months', 'support_calls', 'churned'], dtype='object')

In [154]:
d.columns[d.isnull().any()]

Index([], dtype='object')

In [155]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              300 non-null    int64
 1   monthly_charges  300 non-null    float64
 2   tenure_months    300 non-null    int64
 3   support_calls    300 non-null    int64
 4   churned          300 non-null    int64
dtypes: float64(1), int64(4)
memory usage: 11.8 KB

In [156]:
fd = d.select_dtypes(include=["int64","float64"])
fd

     age  monthly_charges  tenure_months  support_calls  churned
0     22           113.81             57              1        0
1     59            66.97             16              5        1
2     41            20.56             34              1        0
3     56           119.92             37              4        1
4     69            24.78             60              3        0
..   ...              ...            ...            ...      ...
295   23           115.90             56              0        1
296   44            35.21             67              2        1
297   24            25.06             23              5        1
298   29            26.75             26              1        1
299   58            63.55             43              2        1

[300 rows x 5 columns]

In [157]:
fd.corr()

,age,monthly_charges,tenure_months,support_calls,churned
age,1.000000,0.018661,0.026024,0.002825,-0.143743
monthly_charges,0.018661,1.000000,0.064268,-0.050090,0.055267
tenure_months,0.026024,0.064268,1.000000,0.002417,-0.209230
support_calls,0.002825,-0.050090,0.002417,1.000000,0.137387
churned,-0.143743,0.055267,-0.209230,0.137387,1.000000

In [158]:
x=fd[["tenure_months"]]
y=fd["churned"]
x

     tenure_months
0               57
1               16
2               34
3               37
4               60
..             ...
295             56
296             67
297             23
298             26
299             43

[300 rows x 1 columns]

In [159]:
from sklearn.model_selection import train_test_split

In [160]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=32)
x_test

     tenure_months
265             10
255             22
286             18
19              49
212             46
253             39
217             60
297             23
134             15
116             60
181             46
273             39
219             59
29              49
194             45
148             55
179             45
299             43
91              45
8               26
66              41
60              18
263             28
23               5
163             52
44              58
287             11
150              5
214             25
257             54
14              57
131             72
20              43
272             70
56              58
87              17
205              0
101             62
248              2
18               3
54              41
12               6
284             24
180             48
153             28
190              6
17              58
28              23
127             40
191             67
132             23
188             50
251             58
201              5
108             28
269             35
271             37
11              49
45              18
115             22

In [161]:
from sklearn.linear_model import LogisticRegression

In [162]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [163]:
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [164]:
from sklearn.metrics import accuracy_score

In [165]:
accuracy_score(y_test,y_pred)

0.8166666666666667